# These are supported funding model platforms

github: mrz1836
custom: https://mrz1818.com/?tab=tips&utm_source=github&utm_medium=sponsor-link&utm_campaign=postmark&utm_term=postmark&utm_content=postmark
buy_me_a_coffee: mrz1818
